# Generated by Django 4.2.1 on 2023-05-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='login',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
