# Generated by Django 4.2.1 on 2023-05-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
